# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:


services:
    fos_user.doctrine_registry:
        alias: doctrine

    app_bundle.password_resetting:
        class: AppBundle\EventListener\PasswordResettingListener
        arguments: [ @router ]
        tags:
            - { name: kernel.event_subscriber }

    validator.cursoacademico.periodo:
        class: AppBundle\Validator\Constraints\CursoAcademicoPeriodoValidator
        arguments: []
        tags:
            - { name: validator.constraint_validator, alias: cursoacademico.periodo.validator }

    utils.fechas:
        class: AppBundle\Utils\FechasService
        arguments: []

    utils.expediente:
        class: AppBundle\Utils\ExpedienteService
        arguments: [@doctrine.orm.default_entity_manager]