# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:


services:
    fos_user.doctrine_registry:
        alias: doctrine

#    app_bundle.password_resetting:
#        class: AppBundle\EventListener\PasswordResettingListener
#        arguments: [ @router ]
#        tags:
#            - { name: kernel.event_subscriber }

    validator.cursoacademico.periodo:
        class: AppBundle\Validator\Constraints\CursoAcademicoPeriodoValidator
        arguments: []
        tags:
            - { name: validator.constraint_validator, alias: cursoacademico.periodo.validator }

    validator.disciplina.edad:
        class: AppBundle\Validator\Constraints\DisciplinaEdadValidator
        arguments: []
        tags:
            - { name: validator.constraint_validator, alias: disciplina.edad.validator }

    validator.curso.plazas:
        class: AppBundle\Validator\Constraints\CursoPlazasValidator
        arguments: []
        tags:
            - { name: validator.constraint_validator, alias: curso.plazas.validator }

    validator.preinscripcion:
        class: AppBundle\Validator\Constraints\PreinscripcionValidator
        arguments: []
        tags:
            - { name: validator.constraint_validator, alias: preinscripcion.validator }

    validator.prematricula:
        class: AppBundle\Validator\Constraints\PrematriculaValidator
        arguments: ["@doctrine.orm.default_entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: prematricula.validator }

    utils.fechas:
        class: AppBundle\Utils\FechasService
        arguments: []

    utils.expediente:
        class: AppBundle\Utils\ExpedienteService
        arguments: [@doctrine.orm.default_entity_manager]

    utils.curso:
        class: AppBundle\Utils\CursoService
        arguments: [@doctrine.orm.default_entity_manager, @session]

    utils.sorteoplazas:
        class: AppBundle\Utils\SorteoPlazasService
        arguments: [@doctrine.orm.default_entity_manager, @monolog.logger.escuelademusica_sorteo]

    utils.sorteoplazasprematricula:
        class: AppBundle\Utils\SorteoPlazasPrematriculaService
        arguments: ["@doctrine.orm.default_entity_manager", "@monolog.logger.escuelademusica_sorteo"]

    utils.sorteoplazasprematriculav2:
        class: AppBundle\Utils\SorteoPlazasPrematriculaV2Service
        arguments: ["@doctrine.orm.default_entity_manager", "@monolog.logger.escuelademusica_sorteo"]

    utils.listados:
        class: AppBundle\Utils\ListadosService
        arguments: [@doctrine.orm.default_entity_manager, @phpexcel]

    utils:
        class: AppBundle\Utils\UtilsService
        arguments: []

    preinscripcionencurso.form.type.view:
        class: AppBundle\Form\PreinscripcionEnCursoType
        arguments: [ "@utils.curso" ]
        tags:
            - { name: form.type, alias: view }

    prematriculaencurso.form.type.view:
        class: AppBundle\Form\PrematriculaEnCursoType
        arguments: [ "@utils.curso" ]
        tags:
            - { name: form.type, alias: view }

    matricula.form.type.view:
        class: AppBundle\Form\MatriculaType
        arguments: [ "@utils.curso" ]
        tags:
            - { name: form.type, alias: view }