<?php

namespace AppBundle\Repository;

use AppBundle\Entity\CursoAcademico;
use Doctrine\ORM\EntityRepository;

/**
 * AlumnoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlumnoRepository extends EntityRepository
{
    public function getAlumnos($filter)
    {
        $expediente = $filter['expediente'];
        $dni = $filter['dni'];
        $nombre = $filter['nombre'];
        $apellidos = $filter['apellidos'];
        $fechaNacimiento = $filter['fecha_nacimiento'];
        
        $qb = $this->getEntityManager()
            ->createQueryBuilder();
        $query = $qb->select('a')
            ->from('AppBundle:Alumno', 'a');
        if($expediente)
            $query->andWhere(
                $qb->expr()->like('a.expediente', ':expediente')
            )
                ->setParameter('expediente','%'.$expediente.'%');
        if($dni)
            $query->andWhere(
                $qb->expr()->like('a.dni', ':dni')
            )
                ->setParameter('dni','%'.$dni.'%');
        if($nombre)
            $query->andWhere(
                $qb->expr()->like('a.nombre', ':nombre')
            )
                ->setParameter('nombre','%'.$nombre.'%');
        if($apellidos)
            $query->andWhere(
                $qb->expr()->like('a.apellidos', ':apellidos')
            )
                ->setParameter('apellidos','%'.$apellidos.'%');
        if($fechaNacimiento)
            $query->andWhere('a.fechaNacimiento = :fechaNacimiento')
                ->setParameter('fechaNacimiento', $fechaNacimiento);

        $query->orderBy('a.apellidos','ASC');
        
        return $query->getQuery()->getResult();
    }

    public function getNumeroUltimoExpediente(CursoAcademico $cursoAcademico)
    {
        $result = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('MAX(a.expedienteNumero) as numeroMaximo')
            ->from('AppBundle:Alumno', 'a')
            ->where('a.expedienteLetra = :prefijoExpediente')
            ->setParameter('prefijoExpediente', $cursoAcademico->getPrefijoExpediente())
            ->getQuery()
            ->getOneOrNullResult();

        if($result['numeroMaximo'] == null)
            return 0;
        else
            return $result['numeroMaximo'];
    }
}