<?php

namespace AppBundle\Repository;

use AppBundle\Entity\CursoAcademico;
use Doctrine\ORM\EntityRepository;

/**
 * CursoAcademicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CursoAcademicoRepository extends EntityRepository
{
    public function getCursoEnCurso()
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('c')
            ->from('AppBundle:CursoAcademico', 'c')
            ->where('c.enCurso = TRUE')
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function clearEnCurso(CursoAcademico $cursoAcademico)
    {
        $em = $this->getEntityManager();
        $cursosAcademicos = $em->getRepository('AppBundle:CursoAcademico')->findAll();

        foreach ($cursosAcademicos as $c) {
            if ($c != $cursoAcademico) {
                $c->setEnCurso(false);
                $em->persist($c);
            }
        }

        $em->flush();
    }
}
