<?php

namespace AppBundle\Repository;

use AppBundle\Entity\CursoAcademico;
use Doctrine\ORM\EntityRepository;

/**
 * CursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CursoRepository extends EntityRepository
{
    public function getCursos(CursoAcademico $cursoAcademico)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('c')
            ->from('AppBundle:Curso', 'c')
            ->innerJoin('c.cursoAcademico', 'cu')
            ->innerJoin('c.disciplina','d')
            ->where('cu = :cursoAcademico')
            ->setParameter('cursoAcademico', $cursoAcademico)
            ->orderBy('d.nombre','ASC')
            ->getQuery()
            ->getResult();
    }

    public function getCursosEntraEnSorteo(CursoAcademico $cursoAcademico)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('c','p')
            ->from('AppBundle:Curso', 'c')
            ->innerJoin('c.cursoAcademico', 'cu')
            ->innerJoin('c.disciplina','d')
            ->innerJoin('c.preinscripciones','p')
            ->where('cu = :cursoAcademico')
            ->andWhere('c.entraEnSorteo = TRUE')
            ->setParameter('cursoAcademico', $cursoAcademico)
            ->orderBy('d.nombre','ASC')
            ->getQuery()
            ->getResult();
    }

    public function getTotalPlazas(CursoAcademico $cursoAcademico)
    {
        $result = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('SUM(c.numeroPlazas) as total')
            ->from('AppBundle:Curso', 'c')
            ->innerJoin('c.cursoAcademico', 'cu')
            ->innerJoin('c.disciplina','d')
            ->where('cu = :cursoAcademico')
            ->setParameter('cursoAcademico', $cursoAcademico)
            ->orderBy('d.nombre','ASC')
            ->getQuery()
            ->getResult();

        return $result[0]['total'];
    }

    public function findByCursoAcademicoId($cursoAcademicoId)
    {
        $query = $this->getEntityManager()->createQuery(
            "SELECT curso.id as id, disciplina.nombre as disciplinaNombre, disciplinaGrupo.nombre as disciplinaGrupoNombre ".
            "FROM AppBundle:Curso curso ".
            "LEFT JOIN curso.cursoAcademico cursoAcademico ".
            "LEFT JOIN curso.disciplina disciplina ".
            "LEFT JOIN disciplina.disciplinaGrupo disciplinaGrupo ".
            "WHERE cursoAcademico.id = :cursoAcademicoId ".
            "ORDER BY disciplina.nombre ASC"
        )->setParameter('cursoAcademicoId', $cursoAcademicoId);

        return $query->getArrayResult();
    }
}
